### ISSUE TITLE
nested path protected issue

### ISSUE THREAD

**Issue by Vibeesarma** [huntabyte/sveltekit-protected-routes#1]
`<div class="navbar">
	<a href="/" class="btn">Home</a>
	<a href="/protected" class="btn">Protected</a>
	<a href="/protected/item" class="btn">protected-item</a>
	<form action="/logout" method="POST">
		<button class="btn btn-primary">Logout</button>
	</form>
</div>`

put like in the layout and try without login,in this scenario he can access for protected item

**Comment by huntabyte** [comment]
Add a +page.server.ts alongside each of the routes and they cannot. @Vibeesarma
